### PR TITLE
Normalize dashes to ASCII hyphen-minus

### PR DESCRIPTION
**Pull request by Paso**
Normalizes unicode emdash, endash and minus to ASCII hyphen-minus.

### CODE REVIEW

**Comment by Paso** [comment]
@Mitsunee Is there anything I should change to get this ready for merge?

**Comment by Mitsunee** [comment]
Did you run `yarn lint` and `yarn format`? I appear to not yet have workflows for those set up here. Tests seem to pass so this looks good to me so far 👍🏻

**Comment by Paso** [comment]
I ran `yarn format` and lint now and it only changed quotes (' to ")

**Comment by Mitsunee** [comment]
Merged into master, thank you for the PR 👍🏻

**Pull request merged**
